---
title: "RUV Simulation Script"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
devtools::load_all()
```

Simulate the data

```{r}
# Need more automation
ncells <- 20000
nmarkers <- 20

# Biology design matrix
X <- matrix(c(rep(0,floor(ncells/2)), rep(1,ceiling(ncells/2))), ncells, 1) 

# Global mean (similair to overall shift to CyTOF data)
mu <- matrix(rnorm(1*ncells, mean = 10, sd = 1), ncells, nmarkers)

# Coefficients of interest
beta <- matrix(rnorm(1*ncells), 10, nmarkers)
beta[,2] <- rnorm(10, 4, 0.5)
beta[,8] <- rnorm(10, 4, 0.5)
beta[,6] <- rnorm(10, 4, 0.5)

dim(beta)

n_clusters <- 10
clust_size <- 2000
X <- replicate.matrix(rep(1:n_clusters, each = 2000))

# Unwanted variation design matrix
B <- matrix(rbinom(ncells, 1, 0.5), ncells, 1)

# Asssume W uncorrelated
W <- B

# Coeffcients of unwanted variation
alpha <- matrix(rnorm(1*ncells, mean = 20), 1, nmarkers)

# Random error
epsilon <- matrix(rnorm(ncells*nmarkers), ncells, nmarkers)

# RUVIII model
Y <-  mu + X%*%beta + W%*%alpha + epsilon

sample_id <- rep(LETTERS[1:2], each = ncells/2)
cluster_id <- rep(NA, ncells) # Add nonsense to make correct format

data <- data.frame(sample = sample_id, cluster = cluster_id, Y)

data$cluster <- cluster_FlowSOM(data, 10)

colnames(data)[3:(nmarkers+2)] <- paste0("Marker", seq_len(nmarkers))

head(X %*% beta)
```

Plot markers

```{r}
plot_marker_boxplots(data)
```

```{r}
plot_marker_boxplots_samp(data)
```

PCA plots

```{r}
pca <- prcomp(as.matrix(data[, 3:ncol(data)]))

# Look at to what extent the pca vectors captures batch effect
plot(1:ncells, pca$x[,1]) 
plot(1:ncells, pca$x[,2])
plot(1:ncells, pca$x[,3]) 
plot(1:ncells, pca$x[,4]) 
```

```{r}
ggarrange(plotlist = plot_scpca_samp(data, 2000), nrow = 1, ncol = 3, common.legend = TRUE)
```

```{r}
ggarrange(plotlist = plot_scpca_clus(data, 2000), nrow = 1, ncol = 3, common.legend = TRUE)
```

tSNE plots

```{r}
tsne_data <- compute_tsne(data, 1000)
plot_tsne_sample(tsne_data)
plot_tsne_cluster(tsne_data)
```

Normalise the data

```{r}
pca <- prcomp(data[3:ncol(data)])$x

#A1 <- which(X & W)
#A2 <- which(X & !W)
#B1 <- which(!X & W)
#B2 <- which(!X & !W)

M <- matrix(0, nrow = ncells, ncol = 2)

# Incorrect pseudo replicates
#M[sample(c(A1, B1), 1000),1] <- 1
#M[sample(c(A2, B2), 1000),2] <- 1

# Correct psuedo replicates
#M[sample(c(A1, A2), 5000),1] <- 1
#M[sample(c(B1, B2), 5000),2] <- 1

# Random replicates
M[sample(1:ncells, 5000), 1] <- 1
M[sample(1:ncells, 5000), 2] <- 1

# Standardise the cell data
# Could refactor RUVIII wrappers to make this easier
raw_Y <- as.matrix(data[ ,3:ncol(data)])

col_means <- colMeans(raw_Y)
col_sds <- apply(raw_Y, 2, function(x) sd(x))

for(i in 1:ncol(raw_Y)){
  raw_Y[,i] <- (raw_Y[,i] - col_means[i])/col_sds[i]
}

controls <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)

RUVIIout <- fastRUVIII(Y = Y, M, ctl = controls, k = 1)
norm_Y <- RUVIIout$newY
alpha <- RUVIIout$fullalpha
  
  
for(i in 1:ncol(norm_Y)){
  norm_Y[,i] <- norm_Y[,i]*col_sds[i] + col_means[i]
}

norm_data <- data
norm_data[3:ncol(norm_data)] <- norm_Y
```

```{r}
pheatmap::pheatmap(alpha, cluster_cols = FALSE, cluster_rows = FALSE)
```




```{r}
test <- Y - M %*% solve(t(M) %*% M) %*% t(M) %*% Y
pca <- prcomp(test)$x
plot(pca[,1], pca[,2])
```

Plot markers

```{r}
plot_marker_boxplots(norm_data)
```

```{r}
plot_marker_boxplots_samp(norm_data)
```

PCA plots

```{r}
ggarrange(plotlist = plot_scpca_samp(norm_data, 2000), nrow = 1, ncol = 3, common.legend = TRUE)
```

tSNE plots

```{r}
tsne_data <- compute_tsne(norm_data, 2000)
plot_tsne_sample(tsne_data)
```

