---
title: "Simulation Exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Perform the simulation

```{r}
# Could be abstracted into a seperate file (of course)
library(tidyverse)
library(CyTOFFunctions)
library(FlowSOM)
library(ggpubr)
library(cytofkit)
library(ruv)
library(rsvd)

n_pop <- 4
pop_sizes <- c(1000, 1000, 1000, 1000) # sizes of the different populations
pop_means <- c(2, 5, 8, 100) # means of the different populations
pop_sds <- c(0.5, 0.5, 1.0, 2.0) # sds of the different populations
pop_params <- list(pop_means, pop_sds, pop_sizes)

n_markers <- 20 # number of markers
n_cells <- sum(pop_sizes) # total number of cells

create_data <- function(mean, sd, size){
  matrix(rnorm(size * n_markers, mean, sd), ncol = n_markers)
}

sim_data <- do.call(rbind, pmap(pop_params, ~create_data(..1, ..2, ..3)))

sim_data <- asinh((sim_data^10)/5)

colnames(sim_data) <- paste0("Marker", seq_len(n_markers))

sample_ids <- rep(LETTERS[1:2], c(2000, 2000))

clusters <- cluster_FlowSOM(sim_data, 4, seed = 42)

data <- data.frame(sample = sample_ids, cluster = clusters, sim_data)

head(data)
```

PCA Plots

```{r}
# By sample
pca_plot_samp <- plot_scpca_samp(data, N = 4000)
ggarrange(plotlist = pca_plot_samp, nrow = 1,  ncol = 3, common.legend = TRUE)

# By cluster
pca_plot_clus <- plot_scpca_clus(data, N = 4000)
ggarrange(plotlist = pca_plot_clus, nrow = 1,  ncol = 3, common.legend = TRUE)
```

```{r}
tsne_data <- compute_tsne(data, 1000)

# Coloured by sample 
plot_tsne_sample(tsne_data)

# Coloured by cluster
plot_tsne_cluster(tsne_data)
```

Normalise

```{r}
norm_data <- normalise_data(data, norm_clusters = 1, k = 1, num_clusters = 4)
```

```{r}
# By sample
pca_plot_samp <- plot_scpca_samp(norm_data, N = 4000)
ggarrange(plotlist = pca_plot_samp, nrow = 1,  ncol = 3, common.legend = TRUE)

# By cluster
pca_plot_clus <- plot_scpca_clus(norm_data, N = 4000)
ggarrange(plotlist = pca_plot_clus, nrow = 1,  ncol = 3, common.legend = TRUE)
```

```{r}
norm_tsne_data <- compute_tsne(norm_data, 1000)

# Coloured by sample 
plot_tsne_sample(norm_tsne_data)

# Coloured by cluster
plot_tsne_cluster(norm_tsne_data)
```

```{r}
M <- make_M(data$cluster, 1)
Y <- as.matrix(data[,3:ncol(data)])
Y0 <- ruv::residop(Y, M)
YtY <- t(Y0) %*% Y0
YtY
t(svd(YtY)$u) %*% Y
```






